name: Release
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Parse Event
      id: event
      run: |
        echo "::set-output name=tag::$(jq -r '.release.tag_name' "${GITHUB_EVENT_PATH}" | sed s/^v//)"

    - name: Build golang build
      run: |
        VERSION=${{ steps.event.outputs.tag }} ./build.sh

    - name: Upload to release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .change-case-${{ steps.event.outputs.tag }}.alfredworkflow
        asset_name: change-case-${{ steps.event.outputs.tag }}.alfredworkflow
        asset_content_type: application/zip